# Uncomment the next line to define a global platform for your project
platform :ios, '11.0' # Adjust version as needed

target 'jeeva_milk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # React Native configuration
  require_relative '../node_modules/react-native/scripts/react_native_pods'
  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

  # Use React Native with explicit path
  use_react_native!(:path => "../node_modules/react-native")

  # Pods for jeeva_milk can go here

  target 'jeeva_milkTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
